service: swapi

package:
  ## include all files from src
  include:
    - src/**

provider:
  name: aws
  runtime: nodejs18.x
  region: us-west-2

# functions
functions:
  search-person:
    handler: src/infrastructure/http/controllers/person-controller.searchPerson
    events:
      - http:
          path: swapi/person/{id}
          method: get

  search-persons:
    handler: src/infrastructure/http/controllers/person-controller.searchPersons
    events:
      - http:
          path: swapi/persons
          method: get

  create-person:
    handler: src/infrastructure/http/controllers/person-controller.createPerson
    events:
      - http:
          path: swapi/person
          method: post

# Serverless plugins
plugins:
  - serverless-plugin-typescript
  - serverless-offline
